name: RenameItems
main: Wertzui123\RenameItems\Main
version: "3.2"
api: 5.0.0
author: Wertzui123
description: A simple rename plugin
website: https://github.com/Wertzui123/RenameItems
softdepend:
 - FormAPI
permissions:
 renameitems.command.rename:
  default: op
  description: Permission for /rename
 renameitems.command.block:
  default: op
  description: Permission for /block
 renameitems.blockeditems.bypass:
  default: false
  description: Permission for renaming blocked items